# Generated by Django 4.0.4 on 2022-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('estilo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=2)),
                ('data_criacao', models.DateField()),
                ('continente', models.CharField(choices=[('O', 'Oceania'), ('A', 'America'), ('E', 'Europa'), ('F', 'Africa'), ('S', 'Asia'), ('U', 'Unknow')], default='U', max_length=1)),
                ('populacao', models.CharField(max_length=8)),
            ],
        ),
    ]
