# Generated by Django 4.0.4 on 2022-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='sigla',
        ),
        migrations.AlterField(
            model_name='pais',
            name='populacao',
            field=models.CharField(max_length=12),
        ),
    ]
