# Generated by Django 4.0.4 on 2022-04-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turne', '0002_remove_pais_sigla_alter_pais_populacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='nome',
            new_name='pais',
        ),
        migrations.CreateModel(
            name='Turne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('A', 'Acustico'), ('B', 'Banda Completa'), ('S', 'Solo')], default='S', max_length=1)),
                ('cantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turne.cantor')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turne.pais')),
            ],
        ),
    ]
